server:
  port: 8081
spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: Prashant@123AA

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://127.0.0.1:8085


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      hotelRatingBreaker :
        registerHealthIndicator : true
        eventConsumerBufferSize: 10
        failureRateThreshold : 50
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      hotelRatingRetry:
        maxAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod : 4s
        limitForPeriod : 3
        timeoutDuration: 0